export const ACT_TY_CHANGE_MOBILE_MENU_STATE = "CHANGE_MOBILE_MENU_STATE"
export const ACT_TY_CHANGE_DESKTOP_MENU_STATE = "CHANGE_DESKTOP_MENU_STATE"
export const ACT_TY_CHANGE_LOADER_STATE = "CHANGE_LOADER_STATE"

export const ACT_TY_CHANGE_DARK_MODE_STATE = "ACT_TY_CHANGE_DARK_MODE_STATE"

export const ACT_TY_FETCH_SKYSPACE_DETAIL = "ACT_TY_FETCH_SKYSPACE_DETAIL"
export const ACT_TY_SET_SKYSPACE_DETAIL = "ACT_TY_SET_SKYSPACE_DETAIL"

export const ACT_TY_SET_PUBLIC_HASH = "ACT_TY_SET_PUBLIC_HASH"

export const ACT_TY_SET_UPLOAD_LIST = "ACT_TY_SET_UPLOAD_LIST"

export const ACT_TY_FETCH_APPS = "FETCH_APPS"
export const ACT_TY_FETCH_PUBLIC_APPS = "ACT_TY_FETCH_PUBLIC_APPS"
export const ACT_TY_FETCH_ALL_SKYLINKS = "FETCH_ALL_SKYLINKS"
export const ACT_TY_SET_APP = "SET_APP"
export const ACT_TY_FETCH_APPS_SUCCESS = "FETCH_APPS_SUCCESS"
export const ACT_TY_FETCH_APPS_FAILURE = "FETCH_APPS_FAILURE"
export const ACT_TY_SET_APPS = "ACT_TY_SET_APPS"

export const ACT_TY_SET_PUBLIC_IN_MEMORY = "ACT_TY_SET_PUBLIC_IN_MEMORY"

export const ACT_TY_FETCH_APP_DETAIL = "FETCH_APP_DETAIL"
export const ACT_TY_FETCH_SKYSPACE_APP_DETAIL = "FETCH_SKYSPACE_APP_DETAIL"
export const ACT_TY_FETCH_EMPTY_APP = "FETCH_BLANK_APP"
export const ACT_TY_FETCH_APP_DETAIL_SUCCESS = "FETCH_APP_DETAIL_SUCCESS"
export const ACT_TY_FETCH_APP_DETAIL_FAILURE = "FETCH_APP_DETAIL_FAILURE"
export const ACT_TY_CREATE_SKAPP = "CREATE_SKAPP"
export const ACT_TY_CREATE_SKAPP_SUCCESS = "CREATE_APP_SUCCESS"

export const ACT_TY_CHANGE_INFO_MODAL_STATE = "CHANGE_INFO_MODAL_STATE"

export const ACT_TY_FETCH_SKYSPACE_APPS = "FETCH_SKYSPACE_APPS"
export const ACT_TY_FETCH_SKYSPACE_APPS_SUCCESS = "FETCH_SKYSPACE_APPS_SUCCESS"
export const ACT_TY_FETCH_SKYSPACE_APPS_FAILURE = "FETCH_SKYSPACE_APPS_FAILURE"

export const ACT_TY_SET_SKYSPACE_APP_COUNT = "SET_SKYSPACE_APP_COUNT"
export const ACT_TY_FETCH_SKYSPACE_APP_COUNT = "FETCH_SKYSPACE_APP_COUNT"

export const ACT_TY_TRIGGER_SIGNIN = "TRIGGER_SIGN_IN"

export const ACT_TY_SET_USER_SETTING = "SET_USER_SETTING"
export const ACT_TY_FETCH_USER_SETTING = "FETCH_USER_SETTING"

export const ACT_TY_SET_PORTALS_LIST = "SET_PORTALS_LIST"
export const ACT_TY_FETCH_PORTALS_LIST = "FETCH_PORTALS_LIST"

export const EPIC_TY_SET_USER_PROFILE = "EPIC_USER_PROFILE"
export const ACT_TY_SET_USER_PROFILE = "SET_USER_PROFILE"
//export const ACT_TY_GET_USER_PROFILE = "GET_USER_PROFILE"

export const EPIC_TY_SET_USER_PREFERENCES = "EPIC_USER_PREFERENCES"
export const ACT_TY_SET_USER_PREFERENCES = "SET_USER_PREFERENCES"
//export const ACT_TY_GET_USER_PREFERENCES = "GET_USER_PREFERENCES"

export const ACT_TY_SET_MY_FOLLOWERS = "SET_MY_FOLLOWERS"
export const ACT_TY_GET_MY_FOLLOWERS = "GET_MY_FOLLOWERS"

export const ACT_TY_SET_MY_FOLLOWINGS = "SET_MY_FOLLOWINGS"
export const ACT_TY_GET_MY_FOLLOWINGS = "GET_MY_FOLLOWINGS"

export const ACT_TY_SET_USER_SESSION = "SET_USER_SESSION"
export const ACT_TY_SET_SKYDB_USER = "SET_SKYDB_USER"
export const ACT_TY_LOGOUT_SKYDB_USER = "LOGOUT_SKYDB_USER"

export const ACT_TY_SET_DATA_SYNC_STATUS = "SET_DATA_SYNC_STATUS"

export const ACT_TY_SET_SKYSPACE_LIST = "SET_SKYSPACE_LIST"
export const ACT_TY_FETCH_SKYSPACE_LIST = "FETCH_SKYSPACE_LIST"

export const ACT_TY_FETCH_APP_SKYSPACES = "FETCH_APP_SKYSPACES"
export const ACT_TY_FETCH_APP_SKYSPACES_AND_SKYSPACE_APP =
  "FETCH_APP_SKYSPACES_AND_SKYSPACE_APP"
export const ACT_TY_SET_APP_SKYSPACES = "SET_APP_SKYSPACES"
export const ACT_TY_FETCH_APP_SKYSPACES_SUCCESS = "FETCH_APP_SKYSPACES_SUCCESS"
export const ACT_TY_FETCH_APP_SKYSPACES_FAILURE = "FETCH_APP_SKYSPACES_FAILURE"

export const ACTY_TY_SET_HISTORY = "SET_HISTORY"
export const ACTY_TY_FETCH_HISTORY = "FETCH_HISTORY"

export const ACT_TY_SET_IMPORTED_SPACE = "SET_IMPORTED_SPACE"

export const ACT_TY_CHANGE_TOPBAR_STATE = "CHANGE_TOPBAR_STATE"

export const ACT_TY_SET_AUDIO_LIST = "SET_AUDIO_LIST"
export const ACT_TY_ADD_ITEM_IN_AUDIO_LIST = "ADD_ITEM_IN_AUDIO_LIST"
export const ACT_TY_RESET_AUDIO_PLAYER = "RESET_AUDIO_PLAYER"
export const ACT_TY_UPDATE_CURRENT_AUDIO = "UPDATE_CURRENT_AUDIO"
export const ACT_TY_CHANGE_AUDIO_STATUS = "CHANGE_AUDIO_STATUS"

export const ACT_TY_SET_SELECTED_HOSTED_APP ="ACT_TY_SET_SELECTED_HOSTED_APP";


// EPIC Actions
export const ACT_TY_STATS_ACTION = "ACT_TY_STATS_ACTION";
export const EPIC_TY_GET_STATS = "EPIC_TY_GET_STATS";
export const EPIC_TY_SET_STATS = "EPIC_TY_SET_STATS";

export const ACT_TY_AGG_STATS_ACTION = "ACT_TY_AGG_STATS_ACTION";
export const EPIC_TY_AGG_GET_STATS = "EPIC_TY_AGG_GET_STATS";
export const EPIC_TY_AGG_SET_STATS = "EPIC_TY_AGG_SET_STATS";

export const ACT_TY_SET_MY_PUBLISHED_APPS = "ACT_TY_SET_MY_PUBLISHED_APPS";
export const EPIC_TY_PUBLISH_APP = "EPIC_TY_PUBLISH_APP";
export const EPIC_TY_GET_MY_PUBLISHED_APPS = "EPIC_TY_GET_MY_PUBLISHED_APPS";

export const ACT_TY_SET_ALL_PUBLISHED_APPS = "ACT_TY_SET_ALL_PUBLISHED_APPS";
export const EPIC_TY_GET_ALL_PUBLISHED_APPS = "EPIC_TY_GET_ALL_PUBLISHED_APPS";

export const ACT_TY_SET_APP_COMMENTS = "ACT_TY_SET_APP_COMMENTS";
export const EPIC_TY_SET_APP_COMMENTS = "EPIC_TY_SET_APP_COMMENTS";
export const EPIC_TY_GET_APP_COMMENTS = "EPIC_TY_GET_APP_COMMENTS";

export const ACT_TY_CHANGE_SHOW_HOSTING_LINKS_STATE = "ACT_TY_CHANGE_SHOW_HOSTING_LINKS_STATE";

export const ACT_TY_SET_MY_INSTALLED_APPS = "ACT_TY_SET_MY_INSTALLED_APPS";
export const EPIC_TY_INSTALLED_APP = "EPIC_TY_INSTALLED_APP";
export const EPIC_TY_UNINSTALLED_APP = "EPIC_TY_UNINSTALLED_APP";
export const EPIC_TY_GET_MY_INSTALLED_APPS = "EPIC_TY_GET_MY_INSTALLED_APPS";
export const EPIC_TY_INSTALLED_FOR_LOGIN_APP = "EPIC_TY_INSTALLED_FOR_LOGIN_APP";

export const EPIC_TY_SET_DOMAIN = "EPIC_TY_SET_DOMAIN";
export const EPIC_TY_GET_DOMAIN = "EPIC_TY_GET_DOMAIN";
export const ACT_TY_SET_DOMAIN = "ACT_TY_SET_DOMAIN";
export const ACT_TY_GET_DOMAINS = "ACT_TY_GET_DOMAINS";
export const EPIC_TY_DELETE_DOMAIN = "EPIC_TY_DELETE_DOMAIN";
export const EPIC_TY_EDIT_DOMAIN = "EPIC_TY_EDIT_DOMAIN"; 

export const EPIC_TY_SET_STORAGE = "EPIC_TY_SET_STORAGE";
export const EPIC_TY_GET_STORAGE = "EPIC_TY_GET_STORAGE";
export const ACT_TY_SET_STORAGE = "ACT_TY_SET_STORAGE";
export const ACT_TY_GET_STORAGE = "ACT_TY_GET_STORAGE";
export const EPIC_TY_DELETE_STORAGE = "EPIC_TY_DELETE_STORAGE";
export const EPIC_TY_EDIT_STORAGE = "EPIC_TY_EDIT_STORAGE"; 